2023-02-12 19:29:27,128 INFO    MainThread:36932 [wandb_setup.py:_flush():68] Configure stats pid to 36932
2023-02-12 19:29:27,128 INFO    MainThread:36932 [wandb_setup.py:_flush():68] Loading settings from /home/bersi/.config/wandb/settings
2023-02-12 19:29:27,128 INFO    MainThread:36932 [wandb_setup.py:_flush():68] Loading settings from /home/bersi/Documents/CS6910 Assignments/CS6910-Assignment1/wandb/settings
2023-02-12 19:29:27,128 INFO    MainThread:36932 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-02-12 19:29:27,128 INFO    MainThread:36932 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-02-12 19:29:27,128 INFO    MainThread:36932 [wandb_init.py:_log_setup():492] Logging user logs to /home/bersi/Documents/CS6910 Assignments/CS6910-Assignment1/wandb/run-20230212_192927-f7vfns2m/logs/debug.log
2023-02-12 19:29:27,128 INFO    MainThread:36932 [wandb_init.py:_log_setup():493] Logging internal logs to /home/bersi/Documents/CS6910 Assignments/CS6910-Assignment1/wandb/run-20230212_192927-f7vfns2m/logs/debug-internal.log
2023-02-12 19:29:27,128 INFO    MainThread:36932 [wandb_init.py:init():532] calling init triggers
2023-02-12 19:29:27,128 INFO    MainThread:36932 [wandb_init.py:init():538] wandb.init called with sweep_config: {}
config: {}
2023-02-12 19:29:27,128 INFO    MainThread:36932 [wandb_init.py:init():588] starting backend
2023-02-12 19:29:27,128 INFO    MainThread:36932 [wandb_init.py:init():592] setting up manager
2023-02-12 19:29:27,139 ERROR   MainThread:36932 [wandb_init.py:init():1160] error
Traceback (most recent call last):
  File "/home/bersi/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1133, in init
    run = wi.init()
  File "/home/bersi/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 593, in init
    manager._inform_init(settings=self.settings, run_id=self.settings.run_id)
  File "/home/bersi/.local/lib/python3.10/site-packages/wandb/sdk/wandb_manager.py", line 174, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/home/bersi/.local/lib/python3.10/site-packages/wandb/sdk/service/service_sock.py", line 38, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/home/bersi/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/home/bersi/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/home/bersi/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/bersi/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2023-02-12 19:29:47,294 INFO    MainThread:36932 [wandb_setup.py:_flush():68] Configure stats pid to 36932
2023-02-12 19:29:47,294 INFO    MainThread:36932 [wandb_setup.py:_flush():68] Loading settings from /home/bersi/.config/wandb/settings
2023-02-12 19:29:47,294 INFO    MainThread:36932 [wandb_setup.py:_flush():68] Loading settings from /home/bersi/Documents/CS6910 Assignments/CS6910-Assignment1/wandb/settings
2023-02-12 19:29:47,295 INFO    MainThread:36932 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-02-12 19:29:47,295 INFO    MainThread:36932 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-02-12 19:29:47,295 INFO    MainThread:36932 [wandb_init.py:_log_setup():492] Logging user logs to /home/bersi/Documents/CS6910 Assignments/CS6910-Assignment1/wandb/run-20230212_192947-pdv1j9ux/logs/debug.log
2023-02-12 19:29:47,295 INFO    MainThread:36932 [wandb_init.py:_log_setup():493] Logging internal logs to /home/bersi/Documents/CS6910 Assignments/CS6910-Assignment1/wandb/run-20230212_192947-pdv1j9ux/logs/debug-internal.log
2023-02-12 19:29:47,295 INFO    MainThread:36932 [wandb_init.py:init():532] calling init triggers
2023-02-12 19:29:47,295 INFO    MainThread:36932 [wandb_init.py:init():538] wandb.init called with sweep_config: {}
config: {}
2023-02-12 19:29:47,295 INFO    MainThread:36932 [wandb_init.py:init():588] starting backend
2023-02-12 19:29:47,295 INFO    MainThread:36932 [wandb_init.py:init():592] setting up manager
2023-02-12 19:29:47,299 ERROR   MainThread:36932 [wandb_init.py:init():1160] error
Traceback (most recent call last):
  File "/home/bersi/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1133, in init
    run = wi.init()
  File "/home/bersi/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 593, in init
    manager._inform_init(settings=self.settings, run_id=self.settings.run_id)
  File "/home/bersi/.local/lib/python3.10/site-packages/wandb/sdk/wandb_manager.py", line 174, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/home/bersi/.local/lib/python3.10/site-packages/wandb/sdk/service/service_sock.py", line 38, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/home/bersi/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/home/bersi/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/home/bersi/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/bersi/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
